name: Run tests and publish

on:
  push:
    branches:
      - master
      - main
      - beta
    paths:
      - 'src/**/*.ts'
      - 'test/**/*.ts'
      - 'package*.json'
      - '.es*'
      - '.github/workflows/*.yml'
  pull_request:
    branches:
      - master
      - main
      - beta
    paths:
      - 'src/**/*.ts'
      - 'test/**/*.ts'
      - 'package*.json'
      - '.es*'
      - '.github/workflows/*.yml'

jobs:
  test:
    name: 'Build and test on node v${{ matrix.node }}'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [16, 18]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
            node-version: ${{ matrix.node }}

      - name: Install dependencies
        run: npm ci

      - name: Build library
        run: npx tsc -b

      - name: Run version command
        run: ./bin/run --version

      - name: Run help command
        run: ./bin/run --help

      - name: Run code linting
        run: npm run lint

      - name: Run tests
        if: ${{ always() }}
        run: npm run test

  npm-release:
    name: 'Release to npm'
    runs-on: ubuntu-latest
    needs: [test]
    if: github.event_name != 'pull_request'
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use node 16
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Install dependencies
        run: npm ci

      - name: Build library
        run: npm run readme

      - uses: svrooij/secret-gate-action@v1
        id: mygate
        with:
          inputsToCheck: 'NPM_TOKEN'
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v2
        if: steps.mygate.outputs.inputsChecked == 'true'
        id: semantic
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Setup node for Github Registry
        if: steps.semantic.outputs.new_release_published == 'true'
        uses: actions/setup-node@v2
        with:
          node-version: 16
          registry-url: 'https://npm.pkg.github.com'
          scope: 'svrooij'

      - name: Publish To GitHub Package Registry
        if: steps.semantic.outputs.new_release_published == 'true'
        run: |
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
